version: '3'

services:
  dicedistributedgameapplication:
    image: dicedistributedgameapplication
    build:
      context: .
      dockerfile: DiceDistributedGameApplication/Dockerfile

  dicedistributedgameapplication.console:
    image: dicedistributedgameapplication.console
    build:
      context: .
      dockerfile: DiceDistributedGameApplication.Console/Dockerfile


  dicedistributedgameapplication.coreclient:
    image: dicedistributedgameapplication.coreclient
    build:
      context: .
      dockerfile: DiceDistributedGameApplication.CoreClient/Dockerfile

